# Generated by Django 5.1.6 on 2025-02-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafariBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('destination', models.CharField(max_length=255)),
                ('safari_type', models.CharField(choices=[('budget', 'Budget Safari'), ('luxury', 'Luxury Safari'), ('midrange', 'Mid-range Safari')], max_length=20)),
                ('time', models.DateTimeField()),
                ('message', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
