# Generated by Django 5.1.6 on 2025-02-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_safaribooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafariAdventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='safari_adventures/')),
            ],
        ),
    ]
