# Generated by Django 5.1.6 on 2025-02-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_safariadventure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safaripackage',
            name='description',
        ),
        migrations.AddField(
            model_name='safaripackage',
            name='day_1_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='safaripackage',
            name='day_1_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='safaripackage',
            name='day_2_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='safaripackage',
            name='day_2_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='safaripackage',
            name='day_3_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='safaripackage',
            name='day_3_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='safaripackage',
            name='full_description',
            field=models.TextField(default='Experience an unforgettable safari with breathtaking landscapes, diverse wildlife, and luxury accommodations.', help_text='A detailed description covering the safari experience, activities, wildlife, and accommodations.'),
        ),
        migrations.AddField(
            model_name='safaripackage',
            name='overview',
            field=models.TextField(default='An exciting safari adventure filled with wildlife and breathtaking landscapes.', help_text='A short summary of the safari package.'),
        ),
    ]
