# Generated by Django 5.1.6 on 2025-02-14 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_safaripackage_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safaripackage',
            name='day_1_description',
        ),
        migrations.RemoveField(
            model_name='safaripackage',
            name='day_1_title',
        ),
        migrations.RemoveField(
            model_name='safaripackage',
            name='day_2_description',
        ),
        migrations.RemoveField(
            model_name='safaripackage',
            name='day_2_title',
        ),
        migrations.RemoveField(
            model_name='safaripackage',
            name='day_3_description',
        ),
        migrations.RemoveField(
            model_name='safaripackage',
            name='day_3_title',
        ),
        migrations.CreateModel(
            name='SafariItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('safari_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary', to='api.safaripackage')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
    ]
