# Generated by Django 5.1.6 on 2025-02-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_safaripackage_day_1_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='about',
            field=models.TextField(default='Maasai Mara is one of the most famous safari destinations in Kenya.'),
        ),
        migrations.AddField(
            model_name='destination',
            name='features',
            field=models.TextField(default='Big Five spotting, Hot air balloon safari, Maasai cultural experience.'),
        ),
        migrations.AddField(
            model_name='destination',
            name='highlights',
            field=models.TextField(default='Famous for the Great Migration and the Big Five.'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(default='destinations/maasai-mara.jpg', upload_to='destinations/'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='slug',
            field=models.SlugField(default='maasai-mara', unique=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='title',
            field=models.CharField(default='Maasai Mara National Reserve', max_length=255, unique=True),
        ),
    ]
